name: todolist
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  get: ^4.6.6
  image_picker: ^1.0.7
  share_plus: ^7.2.2
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/static/Lora-Bold.ttf
        - asset: assets/fonts/Lora/static/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora/static/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora/static/Lora-SemiBoldItalic.ttf
        - asset: assets/fonts/Lora/static/Lora-Italic.ttf
        - asset: assets/fonts/Lora/static/Lora-Regular.ttf
        - asset: assets/fonts/Lora/static/Lora-Medium.ttf
        - asset: assets/fonts/Lora/static/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora/static/Lora-Medium.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
